### Buscar pessoa
GET http://localhost:3000/get

### Buscar pessoa por id
GET http://localhost:3000/BuscarPorId/1
 
### Cadastrar pessoa
POST http://localhost:3000/newPessoa
Content-Type: application/json

{
    "nome": "Rafael Bruno",
    "idade": 20,
    "cep": "80710150"
}

### Atualizar pessoa
PUT http://localhost:3000/atualizarPessoa
Content-Type: application/json

{
    "idPessoa": 2,
    "nome": "Samuel Comandos",
    "idade": 20,
    "cep": "82960040"
}

### Deletar por Id
DELETE  http://localhost:3000/deletarPessoa/3